source 'https://rubygems.org'
ruby "3.2.2"

gem 'sinatra'
gem 'stripe'
gem 'json'
gem 'dotenv'
gem 'rackup'
gem 'puma'
gem 'rake'
gem 'mechanize'
gem 'executable-hooks'

# Helpful but not required
gem 'sinatra-reloader'
